### ISSUE TITLE
Either infer specs or list them directly

### ISSUE THREAD

**Issue by martinthomson** [ietf-github-services/repo-data#1]
The value for `spec_regex` could be inferred from other information in the repo.  For instance, `draft-[^-]+-${group}-.*` would be serviceable in most cases.

I know that some people use  `draft.md` or similar, but I would prefer to discourage that and require those people to directly list files instead:
```js
{
  "specs": [ "x.md", "y.xml" ]
}
```

The clue here was the fact that you were giving people regular expressions.  That's rarely the right option.

**Comment by mnot** [comment]
I was thinking of trying the "normal" regex first, letting people specify one if that doesn't work. I'd rather not force people to enumerate specs, but yeah, I know, exposing regex sux.
