### ISSUE TITLE
Group things

### ISSUE THREAD

**Issue by martinthomson** [ietf-github-services/repo-data#2]
(The word "group" is doing double duty here.)

You have group_name, group_email, etc..., but it seems like you could use the power of JSON objects to greater effect and encourage people to put group information together by having an object that holds all that information:

```js
{
  "group_info": {
    "full_name": "Unicorns are awesome",
    "email": "unicorns@ietf.org",
    // etc...
  },
}
```

You could get fancy with switch-hitting between a string and an object on the "group" key, but that seems like it would be more confusing.

Also, cross-validation between "primary" and having a value for "group_info" seems like it will only cause problems.

**Comment by mnot** [comment]
That's effectively what it has now; the group info is at the top level for each group, and the repos are under that. Can you make a more concrete suggestion / complaint?

**Comment by martinthomson** [comment]
I take that to mean that you will are expecting to have a repo with no specs and just a group definition.  So why does that repo have to add `group_` to all its fields?

I thought that the example above was pretty concrete.

**Comment by mnot** [comment]
No, the opposite; any repo that's being monitored can declare `primary` and contain the group info.

**Comment by mnot** [comment]
Re-read this and got what you were saying; see commit.

**Comment by martinthomson** [comment]
Glad to see it was just a communication problem.  Thanks.
